CREATE DATABASE Farmacia
GO

USE Farmacia 
GO

CREATE SCHEMA [medicamentos]
GO

CREATE TABLE [PRESENTACION](
[id] INT PRIMARY KEY NOT NULL,
[nombrePresentacion] VARCHAR(100) NOT NULL,
)
GO

CREATE TABLE [TIPOFARMACO](
[id] INT PRIMARY KEY NOT NULL,
[nombreTipoFar] VARCHAR(100) NOT NULL
)
GO
CREATE TABLE [UNIDADMEDIDA](
[id] INT PRIMARY KEY NOT NULL,
[nombreUnidad] VARCHAR(100) NOT NULL,
)
GO

CREATE TABLE [TIPOMEDICAMENTO](
[id] INT PRIMARY KEY NOT NULL,
[nombreTipo] VARCHAR(100) NOT NULL,
[tipoEspecifico] INT NOT NULL,
[unidadMedida] INT NOT NULL,
CONSTRAINT [fk_TipoEspecifico] FOREIGN KEY([tipoEspecifico]) REFERENCES [TIPOESPECIFICO]([id]),
CONSTRAINT [fk_UnidadMedida] FOREIGN KEY([unidadMedida]) REFERENCES [UNIDADMEDIDA]([id])
)
GO

CREATE TABLE [TIPOESPECIFICO](
[id] INT PRIMARY KEY NOT NULL,
[nombreTipEsp] VARCHAR(100) NOT NULL,
)
GO

CREATE TABLE [MEDICAMENTO](
[id] INT PRIMARY KEY NOT NULL,
[nombre] VARCHAR(100) NOT NULL,
[precio] FLOAT NOT NULL,
[presentacion] INT NOT NULL,
[tipoMedicamento] INT NOT NULL,
[cantidad] INT NOT NULL,
[indicaciones] VARCHAR(200) NOT NULL,
[tipoFarmaco] INT NOT NULL,
CONSTRAINT [fk_Presentacion] FOREIGN KEY([presentacion]) REFERENCES PRESENTACION([ID]),
CONSTRAINT [fk_TipoMedicamento] FOREIGN KEY([tipoMedicamento]) REFERENCES TIPOMEDICAMENTO([ID]),
CONSTRAINT [fk_Presentacion] FOREIGN KEY([tipoFarmaco]) REFERENCES TIPOFARMACO([ID])
)
GO



